
email: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
domain: "learnbymaking.wales"

exclude: [src, node_modules, lbm-frontend.config.json, package*, Gemfile*]

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

t:
  en:
    title: Learn by making
    language: English
    root: /en
    updates: Updates
    sessions: Sessions
    labs: The labs
    resources: resources
    powered_by: powered by
    by: by
    cdps:
      name: Centre for Digital Public Services
      url: https://digitalpublicservices.gov.wales/
      acronym: CDPS
  cy:
    title: Dysgu trwy greu
    language: Cymraeg
    root: /cy
    updates: Diweddariadau
    sessions: Sesiynau
    labs: Y labordai
    resources: adnoddau
    powered_by: wedi ei bweru gan
    by: gan
    cdps:
      name: Canolfan Gwasanaethau Cyhoeddus Digidol
      url: https://gwasanaethaucyhoeddusdigidol.llyw.cymru/
      acronym: CGCD
